[project]
name = "RealEstate"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/RealEstate/RealEstate/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.SmartProperty]
path = "contracts/SmartProperty.clar"

[contracts."SmartProperty.clar"]
path = "contracts/SmartProperty.clar.clar"

[contracts.propestatenft]
path = "contracts/propestatenft.clar"

[contracts.realtycontract]
path = "contracts/realtycontract.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
